site_name: Tianyu's Notes
theme:
  name: material
nav:
  - ML Notes:
    - Basic Concepts: ML_Notes/Basic Concepts.md
  - LeetCode:
    - Greedy Algorithm:
      - 核心思想: LeetCode/Greedy Algorithm/核心思想.md
      - 分配问题: 
        - 455 - Assign Cookies: LeetCode/Greedy Algorithm/分配问题/455 - Assign Cookies.md
        - 135 - Candy: LeetCode/Greedy Algorithm/分配问题/135 - Candy.md
      - 区间问题:
        - 435 - Non-overlapping Intervals: LeetCode/Greedy Algorithm/区间问题/435 - Non-overlapping Intervals.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables
  - footnotes
  - attr_list
